<?php namespace JF;
/**

Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-141611
Date:    2018-06-26 09:23:37
Version: v2.1.3
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-141611",
    "email": {
        "to": "{f2}",
        "cc": "tesouraria@ese.ipp.pt",
        "bcc": "treinadordpj@ese.ipp.pt",
        "subject": "Inscri\u00e7\u00e3o em semin\u00e1rio",
        "template": "",
        "sendmail_from": "treinadordpj@ese.ipp.pt"
    },
    "admin": {
        "users": "admin:302b0",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "http:\/\/treinadordpj.ese.ipp.pt\/",
        "message": "Inscri\u00e7\u00e3o submetida. Obrigado!",
        "seconds": "5"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "smtp",
    "smtp": {
        "host": "smtp.office365.com",
        "user": "treinadordpj@ese.ipp.pt",
        "password": "Tdpj2018*",
        "port": "587",
        "security": "tls"
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "Dados do participante",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                }
            },
            "id": "f4",
            "cid": "c25"
        },
        {
            "label": "Nome completo",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-envelope",
                    "leftText": ""
                }
            },
            "id": "f2",
            "cid": "c2"
        },
        {
            "label": "Modalidade",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-child"
                }
            },
            "id": "f5",
            "cid": "c33"
        },
        {
            "label": "N\u00ba C\u00e9dula de treinador",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": []
            },
            "id": "f6",
            "cid": "c38"
        },
        {
            "label": "Anos de experi\u00eancia",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-calendar"
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Campo de preenchimento obrigat\u00f3rio."
                    },
                    "min": {
                        "enabled": false
                    },
                    "alphanumeric": {
                        "enabled": false
                    }
                },
                "mask": {
                    "pattern": "#"
                }
            },
            "id": "f7",
            "cid": "c43"
        },
        {
            "label": "Endere\u00e7o",
            "field_type": "address",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "labelHide": false,
            "gMapApiKey": "",
            "gaCompleteEnabled": false,
            "gaCountryRestrictions": "",
            "gaPostalCodeRestrictions": "",
            "gaLanguage": "",
            "showLabel": true,
            "showPlaceholder": false,
            "showDescription": false,
            "subfields": {
                "addressLine1": {
                    "order": 1,
                    "label": "Rua\/Avenida\/Arruamento",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "street_number route",
                        "gAddressName": "long_name",
                        "placeholder": "1234 Main St.",
                        "description": "Street address, P.O. box, company name, c\/o",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "Campo de preenchimento obrigat\u00f3rio.."
                            }
                        }
                    }
                },
                "addressLine2": {
                    "order": 2,
                    "label": "Address Line2",
                    "field_options": {
                        "enabled": false,
                        "placeholder": "Unit 1234",
                        "description": "Apartment, suite, unit, building, floor, etc.",
                        "validators": {
                            "required": {
                                "enabled": false,
                                "msg": ""
                            }
                        }
                    }
                },
                "city": {
                    "order": 3,
                    "label": "Localidade",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "locality",
                        "gAddressName": "long_name",
                        "placeholder": "City",
                        "description": "City",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "Campo de preenchimento obrigat\u00f3rio."
                            }
                        }
                    }
                },
                "state": {
                    "order": 4,
                    "label": "State \/ Province \/ Region",
                    "field_options": {
                        "enabled": false,
                        "gAddressTypes": "administrative_area_level_1",
                        "gAddressName": "long_name",
                        "placeholder": "State \/ Province \/ Region",
                        "description": "State \/ Province \/ Region",
                        "validators": {
                            "required": {
                                "enabled": false,
                                "msg": "This field is required."
                            }
                        }
                    }
                },
                "postalCode": {
                    "order": 5,
                    "label": "C\u00f3digo Postal",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "postal_code",
                        "gAddressName": "long_name",
                        "placeholder": "Postal \/ Zip Code",
                        "description": "Postal \/ Zip Code",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "Campo de preenchimento obrigat\u00f3rio."
                            }
                        }
                    }
                },
                "country": {
                    "order": 6,
                    "label": "Country",
                    "field_options": {
                        "enabled": false,
                        "gAddressTypes": "country",
                        "gAddressName": "long_name",
                        "placeholder": "Country",
                        "description": "Country",
                        "validators": {
                            "required": {
                                "enabled": false,
                                "msg": "This field is required."
                            }
                        }
                    }
                }
            },
            "id": "f9",
            "cid": "c53"
        },
        {
            "label": "Dados da inscri\u00e7\u00e3o",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                }
            },
            "id": "f10",
            "cid": "c58"
        },
        {
            "label": "Apresenta comunica\u00e7\u00e3o",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Sim",
                        "checked": false,
                        "value": "Sim"
                    },
                    {
                        "label": "N\u00e3o",
                        "checked": false,
                        "value": "N\u00e3o"
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Campo de preenchimento obrigat\u00f3rio."
                    }
                },
                "style": {
                    "columns": "col-2"
                }
            },
            "id": "f11",
            "cid": "c63"
        },
        {
            "label": "Categoria em que se inscreve",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Participante",
                        "checked": false,
                        "value": "Participante"
                    },
                    {
                        "label": "Estudante",
                        "checked": false,
                        "value": "Estudante"
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Campo de preenchimento obrigat\u00f3rio."
                    }
                },
                "style": {
                    "columns": "col-2"
                }
            },
            "id": "f12",
            "cid": "c69"
        },
        {
            "label": "Upload de comprovativo de situa\u00e7\u00e3o de estudante ou ex-estudante (*.pdf)",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": false,
                    "showRemove": true,
                    "allowedFileExtensions": "pdf",
                    "browseLabel": "Procurar"
                },
                "validators": {
                    "required": {
                        "enabled": false
                    }
                }
            },
            "id": "f13",
            "cid": "c74"
        },
        {
            "label": "Pretende inscrever-se em",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Workshop 1",
                        "checked": false,
                        "value": "Workshop 1"
                    },
                    {
                        "label": "Workshop 2",
                        "checked": false,
                        "value": "Workshop 2"
                    },
                    {
                        "label": "Workshop 3",
                        "checked": false,
                        "value": "Workshop 3"
                    },
                    {
                        "label": "Workshop 4",
                        "checked": null,
                        "value": "Workshop 4"
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Campo de preenchimento obrigat\u00f3rio."
                    }
                },
                "style": {
                    "columns": "inline"
                }
            },
            "id": "f14",
            "cid": "c79"
        },
        {
            "label": "Dados de fatura\u00e7\u00e3o",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                }
            },
            "id": "f15",
            "cid": "c84"
        },
        {
            "label": "Nome completo \/ Institui\u00e7\u00e3o",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Campo de preenchimento obrigat\u00f3rio."
                    }
                }
            },
            "id": "f16",
            "cid": "c89"
        },
        {
            "label": "Endere\u00e7o",
            "field_type": "address",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "labelHide": false,
            "gMapApiKey": "",
            "gaCompleteEnabled": false,
            "gaCountryRestrictions": "",
            "gaPostalCodeRestrictions": "",
            "gaLanguage": "",
            "showLabel": true,
            "showPlaceholder": false,
            "showDescription": false,
            "subfields": {
                "addressLine1": {
                    "order": 1,
                    "label": "Rua\/Avenida\/Arruamento",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "street_number route",
                        "gAddressName": "long_name",
                        "placeholder": "1234 Main St.",
                        "description": "Street address, P.O. box, company name, c\/o",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "Campo de preenchimento obrigat\u00f3rio."
                            }
                        }
                    }
                },
                "addressLine2": {
                    "order": 2,
                    "label": "Address Line2",
                    "field_options": {
                        "enabled": false,
                        "placeholder": "Unit 1234",
                        "description": "Apartment, suite, unit, building, floor, etc.",
                        "validators": {
                            "required": {
                                "enabled": false,
                                "msg": ""
                            }
                        }
                    }
                },
                "city": {
                    "order": 3,
                    "label": "Localidade",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "locality",
                        "gAddressName": "long_name",
                        "placeholder": "City",
                        "description": "City",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "Campo de preenchimento obrigat\u00f3rio."
                            }
                        }
                    }
                },
                "state": {
                    "order": 4,
                    "label": "State \/ Province \/ Region",
                    "field_options": {
                        "enabled": false,
                        "gAddressTypes": "administrative_area_level_1",
                        "gAddressName": "long_name",
                        "placeholder": "State \/ Province \/ Region",
                        "description": "State \/ Province \/ Region",
                        "validators": {
                            "required": {
                                "enabled": false,
                                "msg": "This field is required."
                            }
                        }
                    }
                },
                "postalCode": {
                    "order": 5,
                    "label": "C\u00f3digo Postal",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "postal_code",
                        "gAddressName": "long_name",
                        "placeholder": "Postal \/ Zip Code",
                        "description": "Postal \/ Zip Code",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "Campo de preenchimento obrigat\u00f3rio."
                            }
                        }
                    }
                },
                "country": {
                    "order": 6,
                    "label": "Country",
                    "field_options": {
                        "enabled": false,
                        "gAddressTypes": "country",
                        "gAddressName": "long_name",
                        "placeholder": "Country",
                        "description": "Country",
                        "validators": {
                            "required": {
                                "enabled": false,
                                "msg": "This field is required."
                            }
                        }
                    }
                }
            },
            "id": "f17",
            "cid": "c94"
        },
        {
            "label": "NIF",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-check"
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Campo de preenchimento obrigat\u00f3rio."
                    },
                    "max": {
                        "enabled": false
                    },
                    "maxlength": {
                        "enabled": false,
                        "val": "9",
                        "msg": ""
                    }
                },
                "mask": {
                    "pattern": "#"
                }
            },
            "id": "f18",
            "cid": "c99"
        },
        {
            "label": "Upload de comprovativo de pagamento",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": false,
                    "showRemove": true,
                    "allowedFileExtensions": "pdf,png,jpg,jpeg,tif",
                    "browseLabel": "Procurar"
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Campo de preenchimento obrigat\u00f3rio."
                    }
                }
            },
            "id": "f19",
            "cid": "c104"
        },
        {
            "label": "Dados pessoais",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Tomei conhecimento que os dados por mim fornecidos neste formul\u00e1rio ser\u00e3o, unicamente utilizados para a gest\u00e3o de inscri\u00e7\u00f5es neste evento,\nsendo guardados pelo tempo m\u00e1ximo de um ano.",
                        "checked": false,
                        "value": "Sim"
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    }
                },
                "presetJson": "",
                "style": {
                    "columns": "col-1"
                }
            },
            "id": "f22",
            "cid": "c120"
        },
        {
            "label": "Google reCaptcha",
            "field_type": "recaptcha",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                }
            },
            "labelHide": true,
            "recaptcha": {
                "theme": "light",
                "siteKey": "6LfAtlcUAAAAACiW2dpHgmkfnxpZT56hAy422Qk0",
                "secretKey": "6LfAtlcUAAAAAJHF3MgdlH9sFAQeZon-X5Q2yFHL",
                "language": "pt",
                "errMsg": "Google reCaptcha validation error. Please try again.",
                "maxFailed": 3
            },
            "id": "f23",
            "cid": "c125"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "Submeter",
                "icon": "",
                "checkRequiredFields": "Verifique os seguintes campos."
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "f22",
        "saveData": "consent"
    },
    "licenseKey": ""
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class